language: java
sudo: true
jdk:
- openjdk8
before_install:
- chmod +x ./mvnw
script:
- "./mvnw test -B"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: 1014596312@qq.com
  password:
    secure: I3v0JvJYHjCTpepTMP1S6bVon0ADEAZT3vxE/eD0Y8wSCd82XWIo3caKHhi1YBEFD66z213gqFROKWTyKXcmxTR5cAUNk79u/w/sJyYUUT0zggIKEGTjsIKgMZFzxYyDDPe5H4YVvm2f2LsoSr/nmWVcKhVxSoVpl+OL4ClK9A1c6UZGMMoBHnO7vG6pCUN3uCoEMCv4qOGBUhROlGGFkLaIdrGUzDZI69IzmFUNvpsDBbih2ZYJuhUlppq/iVz1rR4WkcqYBDmuh0OEFRQLVKiB9anMRTkMQG64x4giB/SYkSm70vs+vXDWEnNma8cImoIoCh1rHSQPvVc+0digrqkFtnCHmaMHpc1PHPLCYxIV3CA4tnbEA19jZ53V9l9QXBD6W99XZjKw1OrFt/kSaL9Nwc9XXPe4c4VSGTf6NJBOUM7HSMXlHUzLB7G7TlhdgJJmxwbVgd7iZx+MabMr/F6dvb5GeK5Lesb3E0aMbVFb6die8NaY/RUCAMK2OsBMIBq6PSldmubAr0NRjbFt9/seuW32XSdcuDxr2bT0yJQhjIOSBuZyZm/hDpzQWrSMMNxmDe2IRaHJz6HJvIcwT4yn/WD0m2/glvCtfzccXghfep7goNoepVN0zrP/MBTl6rWytqijFVwqMCIwTpqOp2dEfLkmNNGrGCVPuv0TyrI=
  organization: xahhy
  space: development
  on:
    repo: xahhy/ThoughtWorks-Shopping-Spring-Backend
