language: java
jdk:
  - openjdk7
script:
- "./mvnw test -B"
deploy:
  provider: cloudfoundry
  username: 1014596312@qq.com
  password:
    secure: kr2ji3oLvD5X5/23h89LS9uL0h+IDvEWHS4D04rQxpTyhgtJ8Q6G0a2dicfbhrTI4D6cfcA6YAbdgg21rmOnrOYPA8YYQ0j2TWi+2OnABQRBShf/ubxhrZH7EcUOy7CLJ+bi4o31ffoHuEo9PQz4/b1VzAInWsKiykkfw0ranWgBLrW9MlXUMonsefcHPI0lkIu3kJDUcLl9mVGRx+sKc7XmECvDiLPP6JuMOVOSenjhxoT8OGDwfA15cBKN90cVaal46bTYs5qSEiB1HkRQWPzlvx1eVw+WY1dmF6fz4ZaDnusHLnXgVWha7nGvfxYySYBndp7GwMcIs+hGrnQvUgEqZcl2S2C4Dflsr79ivAfyyzSgRG63cVa6oihVCTpB0Vjt3UVbRh4HecnrSbXDiKfT5uZkQ8iRbHprYiKFun9hpAfoIEs9iCtJcKBaGVmowcz63h1kLsrv2K3qyuum6Wl6KcPkLLgWWUNfdpImB08VojZ6A4LPrmdPbdWUBK781mo5W4/g/audeycK414sUArrgida1kzOqUfhqZN0K93SkT104iTOfUG0I6kQ0nRdjw0Ql/iqliZjkglw8aaRLMz9V7IB2D4fHFiPpfuAGoycjA3LGoiqMiCpmpYgrWzopGdXHecLDpR7ftzoYLjYysd3cQHolY+pkX0CDKnwdak=
  api: https://api.run.pivotal.io
  organization: xahhy
  space: development
